### ISSUE TITLE
Can it run on Windows now?

### ISSUE THREAD

**Issue by makisekurisu-jp** [FurkanGozukara/background-replacement#1]
I cloned the repository from huggingface and ran the following error.

`File "D:\AITech\background-replacement\app.py", line 5, in
from background_replacer import replace_background
File "D:\AITech\background-replacement\background_replacer.py", line 23, in
init_segmenter()
File "D:\AITech\background-replacement\segmenter.py", line 37, in init
import models
ModuleNotFoundError: No module named 'models'`

**Comment by FurkanGozukara** [comment]
Yes it is running on windows

Here auto installer : https://www.patreon.com/posts/auto-runpod-for-89919157

**Comment by FurkanGozukara** [comment]
sorry that was for runpod

here for windows : https://www.patreon.com/posts/auto-windows-for-89914747
