### ISSUE TITLE
ModuleNotFoundError: No module named 'data_loader_cache'

### ISSUE THREAD

**Issue by lanyusan** [FurkanGozukara/background-replacement#2]
I tried to run your code but got this error.

It seems your code base doesn't have this module. 

Thanks.

**Comment by FurkanGozukara** [comment]
hello please use this auto installer it works : 

for windows > https://www.patreon.com/posts/auto-windows-for-89914747

for runpod or linux > https://www.patreon.com/posts/auto-runpod-for-89919157

**Comment by smha1012** [comment]
I'm trying to run this code on my Linux server, but I have the same issue.
It looks like [this script](https://github.com/xuebinqin/DIS/blob/main/IS-Net/data_loader_cache.py) is missing.

**Comment by FurkanGozukara** [comment]
> hello please use this auto installer it works :
> 
> for windows > https://www.patreon.com/posts/auto-windows-for-89914747
> 
> for runpod or linux > https://www.patreon.com/posts/auto-runpod-for-89919157

hello. are you using auto installer? because i just recently updated them and working perfect

for windows > https://www.patreon.com/posts/auto-windows-for-89914747

for runpod or linux > https://www.patreon.com/posts/auto-runpod-for-89919157

**Comment by FurkanGozukara** [comment]
> I'm trying to run this code on my Linux server, but I have the same issue. It looks like [this script](https://github.com/xuebinqin/DIS/blob/main/IS-Net/data_loader_cache.py) is missing.

hello. are you using auto installer? because i just recently updated them and working perfect

for windows > https://www.patreon.com/posts/auto-windows-for-89914747

free kaggle notebook attached to this post : https://www.patreon.com/posts/auto-windows-for-89914747

for runpod or linux > https://www.patreon.com/posts/auto-runpod-for-89919157

**Comment by smha1012** [comment]
> > I'm trying to run this code on my Linux server, but I have the same issue. It looks like [this script](https://github.com/xuebinqin/DIS/blob/main/IS-Net/data_loader_cache.py) is missing.
> 
> hello. are you using auto installer? because i just recently updated them and working perfect
> 
> for windows > https://www.patreon.com/posts/auto-windows-for-89914747
> 
> free kaggle notebook attached to this post : https://www.patreon.com/posts/auto-windows-for-89914747
> 
> for runpod or linux > https://www.patreon.com/posts/auto-runpod-for-89919157

I found that your auto installer clones the missing code from the DIS author's repository. 

This was happened because I used your code directly, and in that case, I just pasted the missing code and there was any problem.

Thanks for your reply!
